### ISSUE TITLE
Package doesn't work with the newest version of aws/aws-sdk-php

### ISSUE THREAD

**Issue by RCRalph** [tavux/laravel-ibm-cos#1]
Hello,
Yesterday I decided to update my packages for my Laravel project. During this update, package `aws/aws-sdk-php` was updated  from version `3.173.16` to `3.175.0`.

Now whenever I want to execute anything using `Storage::disk("ibm-cos")`, this error shows up:
`Aws\S3\Exception\S3Exception with message 'Error executing "ListObjects" on "<BUCKETNAME>.https://s3.eu.cloud-object-storage.appdomain.cloud"; AWS HTTP error: cURL error 6: Could not resolve host: <BUCKETNAME>.https (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for <BUCKETNAME>.https://s3.eu.cloud-object-storage.appdomain.cloud'`
Of course `<BUCKETNAME>` is replaced with a real name.

Downgrading the `aws/aws-sdk-php` package to the previously mentioned version solved the problem.

Is there any possibility of this getting fixed in the future?
Thanks for reading and have a nice day.

**Comment by SelimTavukcuoglu** [comment]
Hello, thx for your message and sorry for the late answer. I just pushed yesterday a fix for that.
